export const REFRESH_ACCOUNT_STATE = 'REFRESH_ACCOUNT_STATE';

export const IS_AUTH_SUCCESS = 'IS_AUTH_SUCCESS';
export const IS_AUTH_FAILURE = 'IS_AUTH_FAILURE';
export const IS_AUTH_REQUEST = 'IS_AUTH_REQUEST';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';

export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';
export const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST';
